version: '3.7'
services:
  bot:
    depends_on:
      - db
      - redis
    restart: always
    image: docker.pkg.github.com/vlade11115/python-beginners-garbotdge/garbotdge:1.0
    env_file:
      - .docker-compose.env
  db:
    image: postgres:10
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .docker-compose.env
    ports:
      - "8003:5432"
  redis:
    image: redis:5-alpine
    restart: always
    volumes:
      - ./redis-data:/data