version: '3.7'
services:
  bot:
    depends_on:
      - db
      - redis
    restart: always
    build: .
    env_file:
      - .docker-compose.env
  db:
    image: postgres:10
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .docker-compose.env
    ports:
      - "8003:5432"
  redis:
    image: redis:5-alpine
    restart: always
    volumes:
      - ./redis-data:/data